title: 'Softeam C# Community'
email: StartechDotNet@softeam.fr
description: 'This blog contains posts from various members of Softeam''s C# Community.'
twitter_username: SOFConsulting
github_username: softeamgroup
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
